### ISSUE TITLE
Latest published rules are broken for Bazel 2.0.0

### ISSUE THREAD

**Issue by bmuschko** [bazelbuild/rules_groovy#55]
I receive the following error message when executing the rules v0.0.5 with Bazel 2.0.0. Works fine with Bazel 1.1.0.

```
ERROR: /private/var/tmp/_bazel_bmuschko/db126b824c509a76348765b600ae1c98/external/io_bazel_rules_groovy/groovy/groovy.bzl:434:5: Traceback (most recent call last):
	File "/Users/bmuschko/dev/projects/bazel-examples/groovy/hello-world/WORKSPACE", line 9
		groovy_repositories()
	File "/private/var/tmp/_bazel_bmuschko/db126b824c509a76348765b600ae1c98/external/io_bazel_rules_groovy/groovy/groovy.bzl", line 434, in groovy_repositories
		native.maven_server(<2 more arguments>)
type 'struct' has no method maven_server()
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.202s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

This is my `WORKSPACE` code:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_groovy",
    url = "https://github.com/bazelbuild/rules_groovy/archive/0.0.5.tar.gz",
    sha256 = "d41ca1290de57f2eabc71d5a097689491e3afe7337367a7326396d55db4910f7",
    strip_prefix = "rules_groovy-0.0.5",
)

load("@io_bazel_rules_groovy//groovy:groovy.bzl", "groovy_repositories")
groovy_repositories()
```

Looks to me like [`native.maven_server` does not exist anymore](https://docs.bazel.build/versions/2.0.0/be/workspace.html). I believe you'll have to fully rely on [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) now.

Seems like a [change](https://github.com/bazelbuild/rules_groovy/pull/43/files) has already been made on `master` to remove the use of `native.maven_server`. When are you planning to release a Bazel 2.0.0-compatible rules version?

**Comment by ekuefler** [comment]
I've published 0.0.6 and updated the README. I think things should be working now.
